### ISSUE TITLE
Handle Image Too Large error

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/android-slideshow#18]
This exception is causing the application to crash: 

java.lang.RuntimeException: Canvas: trying to draw too large(xxxbytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)

**Comment by ScreamingHawk** [comment]
Fix in beta
